### ISSUE TITLE
Accessing xenstore-data parameters from powershell

### ISSUE THREAD

**Issue by lynx44** [xenserver/win-xeniface#3]
I very well may be doing something wrong, but I'm unsure how I should be accessing xenstore-data parameters from powershell using the WMI interface.

First I add a parameter from the xenserver CLI:

```
xe vm-param-set uuid=$UUID xenstore-data:vm-data/hostname=test
```

Then I try to retrieve it using powershell:

```
$base = gwmi -n root\wmi -cl CitrixXenStoreBase 
$sid = $base.AddSession("NewSession") 
$session = gwmi -n root\wmi -q "select * from CitrixXenStoreSession where SessionId=$($sid.SessionId)" 

$value = $session.GetValue("vm-data/hostname").Value
echo "Value = $value"
```

However, I'm not seeing a value being returned. This is on a Windows Server 2008 R2 host, patched with the latest updates. I'm running XenServer 6.2 with the latest XenTools. I should also mention that it seems to be connecting properly, because I'm able to retrieve the UUID of the VM by getting the "vm" value like this:

```
$value = $session.GetValue("vm").Value
echo "Value = $value"
```

Is this the correct approach, or am I doing something wrong?

**Comment by lynx44** [comment]
Nevermind, looks like this was user error on my end. I was setting the values after the VM was already started. Looks like the parameters have to be set before the VM starts (or the VM should be restarted).

**Comment by benchalmers** [comment]
That's right.  If you want to write entries to xenstore from within dom 0 without needing to restart the VM, the command you are looking for is xenstore-write (though unlike entries in a xenstore-data parameter, they will be lost when the guest domain is destroyed [e.g. at vm shutdown])
